db:
    build: ./mysql
    volumes:
        - ./mysql/db:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=p455w0rd
        - MYSQL_DATABASE=lls
myphp:
    build: ./php
    links:
        - db
    volumes:
        - ./src:/var/www/html
mynginx:
    build: ./nginx
    ports:
        - "80:80"
    links:
        - db
        - myphp
    volumes:
        - ./src:/var/www/html
